-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\flightControlSystem\flightController_pkg.vhd
-- Created: 2019-01-13 13:16:31
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE flightController_pkg IS
  TYPE vector_of_std_logic_vector32 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(31 DOWNTO 0);
  TYPE matrix_of_std_logic_vector32 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF std_logic_vector(31 DOWNTO 0);
  TYPE vector_of_unsigned79 IS ARRAY (NATURAL RANGE <>) OF unsigned(78 DOWNTO 0);
  TYPE vector_of_signed27 IS ARRAY (NATURAL RANGE <>) OF signed(26 DOWNTO 0);
END flightController_pkg;

