vlib work
vmap -c
vcom  flightController_pkg.vhd
vcom  nfp_add_comp.vhd
vcom  nfp_relop_comp.vhd
vcom  nfp_relop_comp_block.vhd
vcom  nfp_sub_comp.vhd
vcom  nfp_mul_comp.vhd
vcom  Attitude.vhd
vcom  ControlMixer.vhd
vcom  nfp_uminus_comp.vhd
vcom  nfp_sincos_comp.vhd
vcom  XY_to_reference_orientation.vhd
vcom  Yaw.vhd
vcom  equilibrium_thrust.vhd
vcom  nfp_gain_pow2_comp.vhd
vcom  thrustsToMotorCommands.vhd
vcom  Flight_Controller.vhd
vcom  flightController.vhd
